<?php
/**
 * BulkUpdateResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Airtable;

use PSX\Schema\Attribute\Description;

#[Description('')]
class BulkUpdateResponse implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<string>|null
     */
    #[Description('')]
    protected ?array $createdRecords = null;
    /**
     * @var array<string>|null
     */
    #[Description('')]
    protected ?array $updatedRecords = null;
    /**
     * @var array<Record>|null
     */
    #[Description('')]
    protected ?array $records = null;
    /**
     * @param array<string>|null $createdRecords
     */
    public function setCreatedRecords(?array $createdRecords): void
    {
        $this->createdRecords = $createdRecords;
    }
    /**
     * @return array<string>|null
     */
    public function getCreatedRecords(): ?array
    {
        return $this->createdRecords;
    }
    /**
     * @param array<string>|null $updatedRecords
     */
    public function setUpdatedRecords(?array $updatedRecords): void
    {
        $this->updatedRecords = $updatedRecords;
    }
    /**
     * @return array<string>|null
     */
    public function getUpdatedRecords(): ?array
    {
        return $this->updatedRecords;
    }
    /**
     * @param array<Record>|null $records
     */
    public function setRecords(?array $records): void
    {
        $this->records = $records;
    }
    /**
     * @return array<Record>|null
     */
    public function getRecords(): ?array
    {
        return $this->records;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('createdRecords', $this->createdRecords);
        $record->put('updatedRecords', $this->updatedRecords);
        $record->put('records', $this->records);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
