<?php
/**
 * BulkUpdateRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Airtable;

use PSX\Schema\Attribute\Description;

#[Description('')]
class BulkUpdateRequest implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<string>|null
     */
    #[Description('')]
    protected ?array $performUpsert = null;
    #[Description('')]
    protected ?bool $returnFieldsByFieldId = null;
    #[Description('')]
    protected ?bool $typecast = null;
    /**
     * @var array<Record>|null
     */
    #[Description('')]
    protected ?array $records = null;
    /**
     * @param array<string>|null $performUpsert
     */
    public function setPerformUpsert(?array $performUpsert) : void
    {
        $this->performUpsert = $performUpsert;
    }
    /**
     * @return array<string>|null
     */
    public function getPerformUpsert() : ?array
    {
        return $this->performUpsert;
    }
    public function setReturnFieldsByFieldId(?bool $returnFieldsByFieldId) : void
    {
        $this->returnFieldsByFieldId = $returnFieldsByFieldId;
    }
    public function getReturnFieldsByFieldId() : ?bool
    {
        return $this->returnFieldsByFieldId;
    }
    public function setTypecast(?bool $typecast) : void
    {
        $this->typecast = $typecast;
    }
    public function getTypecast() : ?bool
    {
        return $this->typecast;
    }
    /**
     * @param array<Record>|null $records
     */
    public function setRecords(?array $records) : void
    {
        $this->records = $records;
    }
    /**
     * @return array<Record>|null
     */
    public function getRecords() : ?array
    {
        return $this->records;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('performUpsert', $this->performUpsert);
        $record->put('returnFieldsByFieldId', $this->returnFieldsByFieldId);
        $record->put('typecast', $this->typecast);
        $record->put('records', $this->records);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
