<?php
/**
 * CommentReaction automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Airtable;

use PSX\Schema\Attribute\Description;

#[Description('')]
class CommentReaction implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?string $emoji = null;
    #[Description('')]
    protected ?CommentAuthor $reactingUser = null;
    public function setEmoji(?string $emoji) : void
    {
        $this->emoji = $emoji;
    }
    public function getEmoji() : ?string
    {
        return $this->emoji;
    }
    public function setReactingUser(?CommentAuthor $reactingUser) : void
    {
        $this->reactingUser = $reactingUser;
    }
    public function getReactingUser() : ?CommentAuthor
    {
        return $this->reactingUser;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('emoji', $this->emoji);
        $record->put('reactingUser', $this->reactingUser);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
