<?php
/**
 * Record automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Airtable;

use PSX\Schema\Attribute\Description;

#[Description('')]
class Record implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?string $id = null;
    #[Description('')]
    protected ?string $createdTime = null;
    /**
     * @var \PSX\Record\Record<mixed>|null
     */
    #[Description('')]
    protected ?\PSX\Record\Record $fields = null;
    public function setId(?string $id) : void
    {
        $this->id = $id;
    }
    public function getId() : ?string
    {
        return $this->id;
    }
    public function setCreatedTime(?string $createdTime) : void
    {
        $this->createdTime = $createdTime;
    }
    public function getCreatedTime() : ?string
    {
        return $this->createdTime;
    }
    public function setFields(?\PSX\Record\Record $fields) : void
    {
        $this->fields = $fields;
    }
    public function getFields() : ?\PSX\Record\Record
    {
        return $this->fields;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('id', $this->id);
        $record->put('createdTime', $this->createdTime);
        $record->put('fields', $this->fields);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
